[package]
name = "tsl2591"
version = "0.1.0"
authors = ["Paul <pcvonz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.4"
bitfield = "0.13.2"

